FROM python:3.13-slim AS builder

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

RUN apt update && apt install -y \
    build-essential   \
    libcurl4-gnutls-dev \
    default-libmysqlclient-dev     \
    libgnutls28-dev \
    libldap2-dev \
    libsasl2-dev     \
    libxslt1-dev \
    libxml2-dev \
    libffi-dev \
    libgtk-3-0     \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libmemcached-dev \
    libmariadb-dev \
    tzdata \
    libxmlsec1-dev     \
    pkg-config \
    wget

ENV TZ=Europe/Madrid

# Download specific commit from uds-broker repository
ARG UDS_BROKER_COMMIT=5cd8e14
RUN wget -q https://github.com/VirtualCable/uds-broker/archive/${UDS_BROKER_COMMIT}.tar.gz -O /tmp/uds-broker.tar.gz && \
    tar -xzf /tmp/uds-broker.tar.gz -C /tmp && \
    mv /tmp/uds-broker-${UDS_BROKER_COMMIT}*/src /app && \
    cp /tmp/uds-broker-${UDS_BROKER_COMMIT}*/requirements.txt /app/ && \
    rm -rf /tmp/uds-broker*

WORKDIR /app/

RUN pip3 install --no-cache-dir -r requirements.txt
# Stage 2: Production stage
FROM python:3.13-slim

RUN apt update&&apt install -y \
    libgtk-3-0     \
    libpango-1.0-0 \
    libpangoft2-1.0-0 \
    libmemcached-dev \
    libmariadb3 \
    tzdata  \
    pkg-config  

RUN useradd -m -r appuser && \
    mkdir -p /app/log && \
    chown -R appuser /app

# Copy the Python dependencies from the builder stage
COPY --from=builder /usr/local/lib/python3.13/site-packages/ /usr/local/lib/python3.13/site-packages/
COPY --from=builder /usr/local/bin/ /usr/local/bin/

ENV TZ=Europe/Madrid
COPY --from=builder --chown=appuser:appuser /app /app
COPY ./settings.py /app/server/settings.py


WORKDIR /app/
#RUN pip3 install --no-cache-dir -r requirements.txt
#RUN pip3 install --no-cache-dir gunicorn
COPY --chmod=755 <<EOT ./entrypoint.sh
#!/usr/bin/env bash
set -e
gunicorn --preload -b:8000 --env DJANGO_SETTINGS_MODULE=server.settings server.wsgi
EOT
CMD ["./entrypoint.sh"]