services:
  udsbroker:
    ports: 
      - "8000:8000"
    image: "lhzubieta/udsbroker:4.0beta"
    depends_on:
      - mysql
      - memcache
    volumes:
      - assets:/app/static
      - ./server/rsa_key:/app/rsa_key
  taskManager:
    image: "lhzubieta/udsbroker:4.0beta"
    command: "python manage.py taskManager --start --foreground"
    depends_on:
      - mysql
    volumes:
      - ./server/rsa_key:/app/rsa_key
  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: uds
      MYSQL_USER: udsuser
      MYSQL_PASSWORD: udspassword
    volumes:
      - dbdata:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
  mysql-guacamole:
    image: mysql:8.0.27
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamoleuser
      MYSQL_PASSWORD: guacamolepassword
    security_opt:
      - seccomp:unconfined
  memcache:
    image: "memcached:1.6.12-alpine"
  guacd:
    image: "guacamole/guacd:1.5.0"
    ports:
      - "4822:4822"
  guacamole:
    image: "guacamole/guacamole:1.5.0"
    volumes:
      - ./guacamoletunnel:/guacamole_home
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /guacamole_home
      MYSQL_HOSTNAME: mysql-guacamole
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamoleuser
      MYSQL_PASSWORD: guacamolepassword 
    links:
      - guacd
    ports:
      - "8080:8080"
    
  webserver:
    image: caddy:2.5.1
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - assets:/media
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./clients:/media/clients
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - udsbroker
  uds-tunnel-server:
    image: lhusurbil/uds-tunnel-server:4.0beta
    ports: 
      - "7777:7777"
    volumes:
      - ./uds-tunnel/udstunnel.conf:/etc/udstunnel.conf
volumes:
  dbdata:
  assets:
  caddyconfig:
  caddydata:
  clients:
