services:
  broker:
    build:
      context: ./building/broker
      dockerfile: DockerFile
      args:
        OPENUDS_COMMIT: ${OPENUDS_COMMIT:?OPENUDS_COMMIT is required}
    image: uds-broker:4.0-${OPENUDS_COMMIT}
    depends_on:
      - broker-db
      - memcache
    volumes:
      - ./data/broker/assets:/app/static
      - ./data/broker/log:/app/log
      - ./config/broker/rsa_key:/app/rsa_key
      - ./config/broker/settings.py:/app/server/settings.py
  task-manager:
    build:
      context: ./building/broker
      dockerfile: DockerFile
      args:
        OPENUDS_COMMIT: ${OPENUDS_COMMIT:?OPENUDS_COMMIT is required}
    image: uds-broker:4.0-${OPENUDS_COMMIT}
    command: "python manage.py taskManager --start --foreground"
    depends_on:
      - broker-db
    volumes:
      - ./config/broker/rsa_key:/app/rsa_key
      - ./config/broker/settings.py:/app/server/settings.py
  broker-db:
    image: mariadb:${MARIADB_VERSION}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: uds
      MARIADB_USER: udsuser
      MARIADB_PASSWORD: udspassword
    volumes:
      - ./data/broker/db:/var/lib/mysql
  guacamole-db:
    image: mariadb:${MARIADB_VERSION}
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: guacamole
      MARIADB_USER: guacamoleuser
      MARIADB_PASSWORD: guacamolepassword
    volumes:
      - ./data/guacamole/db:/var/lib/mysql
  memcache:
    image: "memcached:1.6"
  guacd:
    image: "guacamole/guacd:1.6.0"
  guacamole:
    image: "guacamole/guacamole:1.6.0"
    volumes:
      - ./config/guacamole:/guacamole_home
    environment:
      GUACD_HOSTNAME: guacd
      GUACAMOLE_HOME: /guacamole_home
      MYSQL_HOSTNAME: guacamole-db
      MYSQL_DATABASE: guacamole
      MYSQL_USER: guacamoleuser
      MYSQL_PASSWORD: guacamolepassword 
    links:
      - guacd
  webserver:
    image: caddy:2.11
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    volumes:
      # Caddy's own documentation suggests mounting a whole directory, not just
      # the Caddyfile so that the whole Caddyfile can be replaced and config
      # reload without the need to recreate the container.
      - ./config/caddy/config:/etc/caddy
      - ./data/broker/assets:/media
      - ./data/caddy/data:/data
      - ./data/caddy/config:/config
      - ./data/broker/clients:/media/clients
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - broker
  tunnel-server:
    build:
      context: ./building/tunnelserver
      dockerfile: DockerFile
      args:
        OPENUDS_COMMIT: ${OPENUDS_COMMIT:?OPENUDS_COMMIT is required}
    image: uds-tunnel-server:4.0-${OPENUDS_COMMIT}
    ports:
      - "7777:7777"
    volumes:
      - ./config/tunnel-server/udstunnel.conf:/etc/udstunnel.conf
      - ./config/tunnel-server/certs:/etc/certs
